pub const MODULES: &[(&str, &str)] = &[
    (
        "00-basics.md",
        include_str!("../content/modules/00-basics.md"),
    ),
    (
        "01-vectors.md",
        include_str!("../content/modules/01-vectors.md"),
    ),
    (
        "02-strings.md",
        include_str!("../content/modules/02-strings.md"),
    ),
    (
        "03-control-flow.md",
        include_str!("../content/modules/03-control-flow.md"),
    ),
    (
        "04-functions.md",
        include_str!("../content/modules/04-functions.md"),
    ),
    (
        "05-collections.md",
        include_str!("../content/modules/05-collections.md"),
    ),
    (
        "06-options-results.md",
        include_str!("../content/modules/06-options-results.md"),
    ),
    (
        "07-files.md",
        include_str!("../content/modules/07-files.md"),
    ),
    (
        "08-ownership-borrowing.md",
        include_str!("../content/modules/08-ownership-borrowing.md"),
    ),
    (
        "09-tuples-structs-enums.md",
        include_str!("../content/modules/09-tuples-structs-enums.md"),
    ),
    (
        "10-traits-generics-lifetimes.md",
        include_str!("../content/modules/10-traits-generics-lifetimes.md"),
    ),
    (
        "11-arrays-slices.md",
        include_str!("../content/modules/11-arrays-slices.md"),
    ),
    (
        "12-iterators.md",
        include_str!("../content/modules/12-iterators.md"),
    ),
    (
        "13-pattern-matching.md",
        include_str!("../content/modules/13-pattern-matching.md"),
    ),
    (
        "14-tests.md",
        include_str!("../content/modules/14-tests.md"),
    ),
    (
        "15-modules-crates.md",
        include_str!("../content/modules/15-modules-crates.md"),
    ),
    (
        "16-error-handling.md",
        include_str!("../content/modules/16-error-handling.md"),
    ),
    (
        "17-cli-input.md",
        include_str!("../content/modules/17-cli-input.md"),
    ),
    (
        "18-smart-pointers.md",
        include_str!("../content/modules/18-smart-pointers.md"),
    ),
];
